# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-16 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20171110_0546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
